# Generated by Django 4.1.7 on 2023-06-20 16:43

from django.db import migrations, models
import django.db.models.deletion
import venues.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_card', models.FileField(blank=True, null=True, upload_to=venues.models.file_upload_to)),
                ('commercial_register', models.FileField(blank=True, null=True, upload_to=venues.models.file_upload_to)),
                ('license_agreement', models.FileField(blank=True, null=True, upload_to=venues.models.file_upload_to)),
                ('rental_contract', models.FileField(blank=True, null=True, upload_to=venues.models.file_upload_to)),
                ('ownership_contract', models.FileField(blank=True, null=True, upload_to=venues.models.file_upload_to)),
                ('national_id', models.FileField(blank=True, null=True, upload_to=venues.models.file_upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('RELIGIOUS', 'Religious'), ('OPEN_AIR', 'Open Air'), ('YACHT', 'Yacht'), ('CONFERENCE', 'Conference'), ('CLASS_HAll', 'Class Hall')], max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('fits_with', models.CharField(max_length=25)),
                ('min_capacity', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('facilities', models.TextField()),
                ('view_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], max_length=10)),
                ('legal_documents', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legalDocs', to='venues.legaldocuments')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.venueowner')),
            ],
        ),
        migrations.CreateModel(
            name='VenueImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=venues.models.venue_image_upload_to)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_images', to='venues.venue')),
            ],
        ),
    ]
