# Generated by Django 4.1.7 on 2023-06-21 21:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 22), null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 22), null=True),
        ),
        migrations.CreateModel(
            name='VenueBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('payment_type', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('event_type', models.CharField(max_length=50)),
                ('request_status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='venues.venue')),
            ],
        ),
    ]
