# Generated by Django 4.1.7 on 2023-06-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_end_date_venue_start_date_venuebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='legal_documents',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legalDocs', to='venues.legaldocuments'),
        ),
    ]
