# Generated by Django 4.1.7 on 2023-06-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_alter_venue_legal_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(choices=[('religious', 'Religious'), ('openair', 'Open Air'), ('yacht', 'Yacht'), ('conference', 'Conference'), ('class hall', 'Class Hall')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venuebooking',
            name='request_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=50),
        ),
    ]
