# Generated by Django 4.1.7 on 2023-06-22 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_alter_venue_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 22, 20, 23, 1, 117630), null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 6, 22, 20, 23, 1, 117630), null=True),
        ),
    ]
