# Generated by Django 4.1.7 on 2023-06-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_alter_venue_end_date_alter_venue_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuebooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
