# Generated by Django 4.1.7 on 2023-06-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0007_venuebooking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuebooking',
            name='request_status',
        ),
        migrations.AlterField(
            model_name='venuebooking',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuebooking',
            name='payment_type',
            field=models.CharField(choices=[('in-person', 'In-Person'), ('online', 'Online')], max_length=50),
        ),
    ]
