# Generated by Django 4.1.7 on 2023-06-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_remove_venuebooking_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='suspended', max_length=10),
        ),
    ]
