# Generated by Django 4.1.7 on 2023-06-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_alter_venue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='legal_documents',
        ),
        migrations.AddField(
            model_name='legaldocuments',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='legalDocs', to='venues.venue'),
            preserve_default=False,
        ),
    ]
