# Generated by Django 4.1.7 on 2023-06-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='venuebooking',
            name='request_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='venue',
            name='max_capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='min_capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
