# Generated by Django 4.1.7 on 2023-06-29 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0012_venue_rate_venuebooking_request_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteVenues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ManyToManyField(related_name='favouriteVenues', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ManyToManyField(to='venues.venue')),
            ],
        ),
    ]
