# Generated by Django 4.1.7 on 2023-06-30 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0014_alter_venue_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritevenues',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favouritevenues',
            name='venue',
        ),
        migrations.AddField(
            model_name='favouritevenues',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favouriteVenues', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favouritevenues',
            name='venue',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='venues.venue'),
            preserve_default=False,
        ),
    ]
