# Generated by Django 4.1.7 on 2023-06-30 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0015_remove_favouritevenues_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritevenues',
            unique_together={('user', 'venue')},
        ),
    ]
