# Generated by Django 4.1.7 on 2023-07-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0017_alter_venue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='phone_number',
            field=models.CharField(default='0223974559', max_length=15),
            preserve_default=False,
        ),
    ]
