# Generated by Django 4.1.7 on 2023-06-29 13:07

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_event_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=events.models.upload),
        ),
    ]
