# Generated by Django 4.1.7 on 2023-06-30 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_rename_title_ticket_type_eventbooking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='favouriteevent',
            name='user',
        ),
        migrations.AddField(
            model_name='favouriteevent',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favouriteevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favouriteEvents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
