# Generated by Django 4.1.7 on 2023-07-03 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_favouriteevent_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='quantity',
            field=models.PositiveIntegerField(default='0228513990'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='ticket',
            field=models.ForeignKey(default='01136922086', on_delete=django.db.models.deletion.PROTECT, to='events.ticket'),
            preserve_default=False,
        ),
    ]
