# Generated by Django 4.1.7 on 2023-07-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventbooking_quantity_eventbooking_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='payment_id',
            field=models.CharField(default='AXya12387', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
