# Generated by Django 4.1.7 on 2023-07-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventbooking_payment_id_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
