# Generated by Django 4.1.7 on 2023-07-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('capacity', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=100)),
                ('event_planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.eventplanner')),
            ],
        ),
        migrations.CreateModel(
            name='WorkImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('previous_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.previouswork')),
            ],
        ),
    ]
