# Generated by Django 4.1.7 on 2023-07-04 20:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_previouswork_workimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to_prev_work),
        ),
    ]
