# Generated by Django 4.1.7 on 2023-07-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_workimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimages',
            name='previous_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.previouswork'),
        ),
    ]
