# Generated by Django 3.2.20 on 2023-07-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp_work_images'),
        ),
    ]
